### ISSUE TITLE
error while loading shared libraries: libnss3.so

### ISSUE THREAD

**Issue by ostrolucky** [dunglas/panthere#7]
So, wanted to give a go to this project. When running example in readme, this happens:
```
Fatal error: Uncaught RuntimeException: /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/ProcessManager/../../chromedriver-bin/chromedriver_linux64: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
 in /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/ProcessManager/WebServerReadinessProbeTrait.php:62
Stack trace:
#0 /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/ProcessManager/ChromeManager.php(48): Panthere\ProcessManager\ChromeManager->waitUntilReady(Object(Symfony\Component\Process\Process), 'http://127.0.0....')
#1 /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/Client.php(65): Panthere\ProcessManager\ChromeManager->start()
#2 /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/Client.php(236): Panthere\Client->start()
#3 /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/Client.php(156): Panthere\Client->get('http://api-plat...')
#4 /root/.composer/vendor-bin/dunglas/test.php(6) in /root/.composer/vendor-bin/dunglas/vendor/dunglas/panthere/src/ProcessManager/WebServerReadinessProbeTrait.php on line 62
```

**Comment by Kocal** [comment]
Hey, how did you solve it?

**Comment by ostrolucky** [comment]
yes

**Comment by darul75** [comment]
just to say when executing this type of command from your pipeline like jenkins it can be useful to bypass the prompt (y/n) by passing this extra param.

`apt --assume-yes intall {dep}`
